version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo:latest
    ports:
      - "27018:27018"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: